server:
  port:8080

build.name: @project.name@
build.version: @project.version@
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/abc_tech
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jpa:
  hibernate:
    ddl-auto: create


